#!/usr/bin/env zsh

# Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
targz() {
    local tmpFile="${1%/}.tar"
    tar -cvf "${tmpFile}" "${1}" || return 1

    size=$(stat -c"%s" "${tmpFile}" 2> /dev/null)

    local cmd=""
    if [[ $size -lt 52428800 ]] && [[ -n $(command -v zopfli) ]]; then
        # the .tar file is smaller than 50 MB and Zopfli is available; use it
        cmd="zopfli"
    else
        if [[ -n $(command -v pigz) ]]; then
            cmd="pigz"
        else
            cmd="gzip"
        fi
    fi

    echo "Compressing .tar using \`${cmd}\`…"
    "${cmd}" -v "${tmpFile}" || return 1
    [[ -f "${tmpFile}" ]] && rm "${tmpFile}"
    echo "${tmpFile}.gz created successfully."
}